### ISSUE TITLE
Error: invalid argument to unary operator with plotting code in Rmd file (Ref: Lab 01, Ex 5)

### ISSUE THREAD

**Issue by wilburk** [Sta199-S18/community#11]
The first time I ran the given code for exercise 5, the appropriate amalgamation of the 13 plots appeared in my viewer. 
```
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```
Once I inputed this exact code into lab-01-hello-rRMD, I got the following error message: 
<img width="744" alt="screen shot 2018-01-21 at 1 49 37 am" src="https://user-images.githubusercontent.com/35311617/35191599-6a3fe23e-fe4d-11e7-8418-0f26c6339a48.png">
Why is the code no longer working? Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
I wasn't sure initially, so I googled the error and came across this: https://stackoverflow.com/questions/17240536/r-unary-operator-error-from-multiline-ggplot2-command.

See the top answer, which suggests you might have copied and pasted from the console and hence inadvertently adding those extra `+`s at the beginning of the lines (which in the console means the code is continuing but are not needed in your Rmd file).

Take a look to see if this is the issue, if not, we can dig a bit deeper.

**Comment by mine-cetinkaya-rundel** [comment]
@wilburk if this works, feel free to close the issue

**Comment by wilburk** [comment]
Yep, this fixed everything! Thank you, and see you tomorrow
