### ISSUE TITLE
GitHub Repo: gitignore, README, graphs not showing up

### ISSUE THREAD

**Issue by jamiepalka** [Sta199-S18/community#13]
@mine-cetinkaya-rundel Hi! At the end of the lab, it says "Before you wrap up the assignment, make sure all documents are updated on your GitHub repo." Are these the .gitignore and README.md, etc. documents? What changes should have been made to these?  Also, I can see all final changes made to the main file, but the graphs aren't showing up when I view the document (all instructions are, though), is that ok?  Thank you so much!

**Comment by mine-cetinkaya-rundel** [comment]
@jamiepalka Yes, all files should be pushed to GitHub. We'll talk more about the .gitignore next time, for now you can just push it.

The graphs not showing up is ok for now, but I will discuss how to get them to show up in class this week.

**Comment by garylarson** [comment]
It looks like this issue can be closed. @jamiepalka feel free to re-open it if needed.
