### ISSUE TITLE
Pushed the wrong commit

### ISSUE THREAD

**Issue by MalaviRavindran** [Sta199-S18/community#14]
I edited exercise 4, knitted, and committed with the message: "Added answer for Ex 5" instead of Ex 4 by accident. I already pushed the wrongly named commit. When I try to alter the name of the commit and push that, it gives me an error message: "Updates were rejected because the tip of your current branch is behind its remote counterpart. Integrate the remote changes (e.g. 'git pull ...') before pushing again." What do I do?

**Comment by mine-cetinkaya-rundel** [comment]
First, the content of the commit message is actually not checked by any automated tool -- we look over them to make sure you're writing reasonable commit messages but R/Git doesn't care about the content of the message.

The error you mention is surprising though, as it suggests that a change was made on the GitHub repo (as opposed to in RStudio). Try following the directions, click on Pull. What happens?

Note: You won't be able to change your commit message from earlier (at least not easily), but that's ok.
