### ISSUE TITLE
Error in install.packages : subscript out of bounds

### ISSUE THREAD

**Issue by carmstrong1** [Sta199-S18/community#15]
Hello,

Some text that said "Error in install.packages : subscript out of bounds" appeared in my console when I was installing the tidyverse package. What does this mean? 

*I went back and deleted everything I'd done in the console and tried to install everything a second time. This time I waited until the tidyverse package had completely installed before entering the datasauRus package text because I suspected that installing the datasauRus package before the tidyverse package had totally installed was what led to the error in install.packages: subscript out of bounds. I didn't get the error this time. Was the error due to prematurely installing the datasauRus package?

Thank you.

**Comment by garylarson** [comment]
I'm not sure why that error occurred. I think R executes commands sequentially, meaning if you entered `install.packages('tidyverse')`  and then _before it was finished_, tried to execute `install.packages('datasauRus')`, you ought to be fine. 

Moreover, if package B requires package A and you forgot to install package A first, then executing  `install.packages('B')` ought to trigger a prompt that asks you to install A (or it will do it automatically). 

So, I don't have a great answer for you, but good job troubleshooting it anyway!

**Comment by carmstrong1** [comment]
Thank you!

**Comment by mine-cetinkaya-rundel** [comment]
Interesting @carmstrong1. I'm thinking the installation may have been interrupted for some reason the first time around, and hence you got the error.
