### ISSUE TITLE
Error in filter(dataset == "circle") : object 'dataset' not found

### ISSUE THREAD

**Issue by GarrettH96** [Sta199-S18/community#19]
I am having an issue with Ex 4. All of the other datasets have been running smoothly, however the 'circle' dataset is giving me this error after I type the first line of code:

```r
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

Error in filter(dataset == "circle") : object 'dataset' not found
```

Is there a quick fix for this problem?

Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
Have you tried running this in your R Markdown file where you know for sure the `datasauRus` package is loaded?
