### ISSUE TITLE
Submitting

### ISSUE THREAD

**Issue by GerardoParraga** [Sta199-S18/community#20]
In the last part of the lab it says:  "Before you wrap up the assignment, make sure all documents are updated on your GitHub repo." 

Where can I check that? Is that just where we're supposed to see all of the commits?

**Comment by ptorres09** [comment]
I am having the same problem. I am not sure how to make sure that all of the documents are updated on my Github repo.

**Comment by mine-cetinkaya-rundel** [comment]
In the GitHub org for this course you should be able to see your own reps: https://github.com/Sta199-S18
