### ISSUE TITLE
options(digits = 2) not working

### ISSUE THREAD

**Issue by cmw78** [Sta199-S18/community#23]
adding the options(digits = 2) line doesn't seem to change my output- any ideas?

**Comment by emilyfalcon** [comment]
We are also having this problem... @cmw78 have you found a solution yet?

**Comment by cmw78** [comment]
I haven't :(

**Comment by emilyfalcon** [comment]
@mine-cetinkaya-rundel we can't seem to figure out how to change options(digits=2). Any suggestions?

**Comment by WalkerHarrison** [comment]
Many groups have had this issue and I can't seem to get the desired behavior myself using `options(digits = 2)`. We'll try to get to the bottom of it, but for now you can try the alternative method for showing just two places past the decimal (using `mutate` and `round`).

**Comment by cmw78** [comment]
<img width="918" alt="screen shot 2018-01-31 at 10 58 05 pm" src="https://user-images.githubusercontent.com/16271014/35660491-4420fa30-06da-11e8-86a0-00b4494e667f.png">

This is what I tried!

**Comment by mine-cetinkaya-rundel** [comment]
These values are getting rounded. Try running the code without the options set, and you will observe the difference.
