### ISSUE TITLE
How to find proportion rather than just quantity

### ISSUE THREAD

**Issue by MalaviRavindran** [Sta199-S18/community#25]
Hi! I had a question for exercise 2. It says that we have to put the proportion of women in each field in a table. I was wondering how I could get the proportion, rather than just the total number. Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
Take a look at the codebook, which variable gives us this information?

**Comment by mine-cetinkaya-rundel** [comment]
Need more help on this or shall we close?
