### ISSUE TITLE
Exercise 1 Question

### ISSUE THREAD

**Issue by MalaviRavindran** [Sta199-S18/community#28]
When I type "options(digits = 2)," it doesn't seem to be doing anything to the data in the table. If i remove it, the data is the same. Should all of the numbers have 2 significant figures? 
I am typing:

options(digits = 2)
college_recent_grads %>%
  arrange(unemployment_rate) %>%
  select(rank, major, unemployment_rate)

When I run it with or without the options(digits = 2), the table looks the same. Am I putting the line in the wrong place?

**Comment by MalaviRavindran** [comment]
never mind, i got it!

**Comment by mine-cetinkaya-rundel** [comment]
👍
