### ISSUE TITLE
Running library(tidyverse) in console gives an error

### ISSUE THREAD

**Issue by emilyfalcon** [Sta199-S18/community#29]
I installed tidyverse in my console and then ran library(tidyverse) and got this error:
[2018-02-01 18:40:25] [error] handle_read_frame error: websocketpp.transport:7 (End of File)

**Comment by mine-cetinkaya-rundel** [comment]
This may be a connectivity issue. Are you able to use functionality of the
package despite this message?
On Thu, Feb 1, 2018 at 10:43 AM Emily Falcon <notifications@github.com>
wrote:

> I installed tidyverse in my console and then ran library(tidyverse) and
> got this error:
> [2018-02-01 18:40:25] [error] handle_read_frame error:
> websocketpp.transport:7 (End of File)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Sta199-2DS18_community_issues_29&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=VMaFnDxOO7DFh_jmcYrq6Oi2_V_d1YoR6dsQ-kCSJjw&m=UHe3cNW9UzUld3rG4EYZQtEpIEp82zvwVmmQy7GR3gY&s=LWTub3gj-HrtBm7wp-UZwlhs6SJW5JtkfMctVGkNYgs&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFsHUdHiaFyAx1ZPhiCOL17trr98XSMMks5tQgWqgaJpZM4R2F8X&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=VMaFnDxOO7DFh_jmcYrq6Oi2_V_d1YoR6dsQ-kCSJjw&m=UHe3cNW9UzUld3rG4EYZQtEpIEp82zvwVmmQy7GR3gY&s=50keUgNctLUi49YMMym5usMRz3GDRUNTpbzYpz476RM&e=>
> .
>
-- 
Mine Çetinkaya-Rundel, Ph.D.
Director of Undergraduate Studies
Associate Professor of the Practice
Duke University, Department of Statistical Science
<mine@stat.duke.edu> mine@stat.duke.edu
<https://stat.duke.edu/~mc301/> https://stat.duke.edu/~mc301
<https://github.com/mine-cetinkaya-rundel>  <https://twitter.com/minebocek>
<http://citizen-statistician.org/>

**Comment by mine-cetinkaya-rundel** [comment]
@emilyfalcon is this resolved?

**Comment by emilyfalcon** [comment]
@mine-cetinkaya-rundel I re-started RStudioCloud and didn't get the message again. I did have the function of the package even with the error, though!
