### ISSUE TITLE
Where is Appendix in UNVotes?

### ISSUE THREAD

**Issue by jamiepalka** [Sta199-S18/community#3]
@mine-cetinkaya-rundel @garylarson Where is the Appendix located in the UNVotes project when opened in RStudio cloud? Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
@jamiepalka The Appendix isn't a separate file, it's a section in the document. It's at the very bottom of the document, marked with `##`. Does this answer your question? If I misinterpreted it please feel free to post a follow up.
