### ISSUE TITLE
Lab3 Ex10: Filter for 1000 sq miles?

### ISSUE THREAD

**Issue by elizabethbartusiak** [Sta199-S18/community#30]
Hello!
On lab 3, exercise 10, the question asks: Which states have the most Denny’s locations per thousand square miles? What about La Quinta?
Then, the lab steps through creating a "map" of the US with the locations. Is this map the answer for exercise 10? Or are we supposed to give an exact answer? If so, what is the best way to go about filtering the data for every 1000 square miles?
Thanks in advance for the clarification!

**Comment by mine-cetinkaya-rundel** [comment]
The answer to Ex 10 is not the map.

To go about answering Ex 10, which asks for number of locations per square miles, we need to calculate this value. Take a look at the output of

```
dn %>%
  count(state) %>%
  inner_join(states, by = c("state" = "abbreviation"))
```

What does this give us -- which variables? How can we use these variables to calculate the value we need? Think about how you would do it for one state first. Then, remember that we can construct a new variable based on others using `mutate`. Feel free to continue the conversation below if more hints would be useful.
