### ISSUE TITLE
Longitude and Latitude

### ISSUE THREAD

**Issue by lzerbino** [Sta199-S18/community#31]
Hi, 

When trying to plot dn_lq I was unable to because I dont have longitude and latitude in my data frame anymore. How do I recover it without changing everything?

**Comment by mine-cetinkaya-rundel** [comment]
@lzerbino you shouldn't be removing these variables from your data frame. can you backtrack to see where you lost them? 

you shouldn't have to re-do anything. you'll just need to fix the code and re-knit your document. happy to help if you can give some more detail on where you're removing these variables.

**Comment by lzerbino** [comment]
They were lost with the 

lq <- lq%>% 
  count(state) %>%
  inner_join(states, by = c("state" = "abbreviation")) %>%
  arrange(desc(n))

code chunk.

**Comment by lzerbino** [comment]
I removed '<-lq' and now it doesn't find the object 'area' when i am doing n/over area times 1000

**Comment by lzerbino** [comment]
it works for lq but not for dn

**Comment by mine-cetinkaya-rundel** [comment]
@lzerbino It makes sense that they were lost in that stage, because the second line in the pipe (`count(state)`) will leave you with a data frame that just has `state` and `n`. Assigning the result of this back to the original data frame is not necessary, and in fact, you should avoid it.
