### ISSUE TITLE
HW Ex 1

### ISSUE THREAD

**Issue by lzerbino** [Sta199-S18/community#35]
![screenshot 2018-02-08 11 37 17](https://user-images.githubusercontent.com/35470668/35985512-cb8415f8-0cc4-11e8-8f7b-3e67f940682e.png)

**Comment by mine-cetinkaya-rundel** [comment]
@lzerbino I see there's an error, but what's the question?

**Comment by lzerbino** [comment]
I am wondering why it is not working

**Comment by mine-cetinkaya-rundel** [comment]
So you're creating a new variable called `diffinheight`. And you're setting it *equal to* the differences in heights. In this case you have a syntax error in setting a variable to be equal to something. Can you spot it?
