### ISSUE TITLE
Homework 2 Question 2

### ISSUE THREAD

**Issue by mitrakic** [Sta199-S18/community#36]
For the replication of the graph, how precise do we have to be? I have all the main parts replicated, but some theme elements are a bit different, for example my font sizes all look smaller. I think this is because I changed the theme of my rmarkdown through rstudio earlier in the course, but I can't remember how we did that, and I'm not sure if it's something I need to replicate for this problem.

**Comment by mine-cetinkaya-rundel** [comment]
Your markdown theme would not affect the plot. 

Font sizes shouldn't matter, you don't need to worry about that -- that can be about the sizing of the image when posted.
