### ISSUE TITLE
Lab Grading Questions/Concerns

### ISSUE THREAD

**Issue by jamiepalka** [Sta199-S18/community#38]
My lab group got points off of lab 02 that I think we should have gotten.  Do I reach out to the TA who graded it for questions about this?  

Also, for lab 02, we got points off for not having all members commit.  After the concept of the "leader" was explained to us by our TA, we thought that purpose of the leader was to type while everyone follow along and talk each question out during lab.  We explicitly asked our TA if having one person type was okay, and he said yes.  We got together for about 2 hours the Sunday after the lab was assigned to finish the lab, and while everyone didn't commit, we all contributed very equally.  I typed, while everyone followed along and sent me snippets of code to use.  We didn't how to work with merge conflicts/pulling at the time we worked on the lab.  By the time you explained how to resolve merge conflicts in class, we had already finished the lab, and never thought to go back and have people commit since we were never told that points would be taken off for this.  I hope that makes sense - sorry to be so wordy. @mine-cetinkaya-rundel

**Comment by mine-cetinkaya-rundel** [comment]
@jamiepalka see under regrade requests at http://www2.stat.duke.edu/courses/Spring18/Sta199/policies/ -- there's a link to a form
