### ISSUE TITLE
Hw 2 question 2

### ISSUE THREAD

**Issue by MalaviRavindran** [Sta199-S18/community#39]
I am struggling with making the graph... 
I have gotten to the point where I have this table:
## 6 Pidgey   Tackle          22

But I am unsure of how to get it to a double bar graph from here, where even though the species is repeated in the table, it only shows up once on the graph with two bars.
Thank you!

**Comment by mine-cetinkaya-rundel** [comment]
You don't need to make a table, you can directly use the `ggplot` function. Some hints:

- Figure out which geom you need
- Start with the variable on the x axis
- Take a look at the options for the specific geom you need at http://ggplot2.tidyverse.org/reference/index.html and use a trial/error method
