### ISSUE TITLE
Is 1/17 lecture recorded?

### ISSUE THREAD

**Issue by cimerberg** [Sta199-S18/community#4]
@mine-cetinkaya-rundel Is the online lesson from today recorded anywhere or was it just a one-time livestream?

**Comment by mine-cetinkaya-rundel** [comment]
I'm afraid not! I tried to record but it doesn't seem like it worked (I've had issues with recording and WebEx before). However I'll do some screencasts in place of tomorrow's labs now that those are cancelled too, and between those and slides and asking questions here/office hours you should be covered!
