### ISSUE TITLE
What to include for question where answer is already given? (Ref: Lab 01, Ex 2)

### ISSUE THREAD

**Issue by MalaviRavindran** [Sta199-S18/community#5]
Quick question about exercise 2. It says "Basically, the answer is already given, but you need to include relevant bits in your Rmd document and successfully knit it and view the results" and to "clean up some of the narrative so that it only includes what you want to turn in." What parts do we not want to turn in? And what relevant information do we need to include apart from what is already there?

**Comment by mine-cetinkaya-rundel** [comment]
In the lab template I had some extra instructions in parentheses, those will need to be removed. You might update the tiny bit of existing narrative (but you don't have to). Really what you need to do for this question is minimal.

PS: I updated your question title to be more informative to others who might come here looking for answers on the same thing.

**Comment by garylarson** [comment]
Looks like this has been solved. I'm closing the issue.
