### ISSUE TITLE
How to tell how many columns are in a data frame? (Ref: Lab 01, Ex 1)

### ISSUE THREAD

**Issue by jtouma3** [Sta199-S18/community#6]
After pulling up the help file for the `datasaurus_dozen`, the information provided does not include # of columns (only rows and variables). Is there somewhere else I should look for column count?

**Comment by mine-cetinkaya-rundel** [comment]
@jtouma3 variables are represented as columns, the number of which are given in the help file.

Another alternative, outside the scope of this exercise but will be useful later on, is the `ncol` function:

```r
ncol(datasaurus_dozen)
```

**Comment by garylarson** [comment]
Looks like this has been solved. I'm closing the issue.
