### ISSUE TITLE
Error: status code 403 returned

### ISSUE THREAD

**Issue by ValerieRoberts** [Sta199-S18/community#9]
datasauRus downloaded then gave me "[2018-01-19 21:06:04] [error] handle_read_frame error: websocketpp.transport:7 (End of File)". When I tried to re-download, I got "Error: status code 403 returned"

**Comment by mine-cetinkaya-rundel** [comment]
This doesn't seem like an installation issue, but rather an RStudio Cloud issue. Have you tried restarting the session (just log out and log back in)? If that doesn't work, please post again here and I'll try to diagnose.

**Comment by mine-cetinkaya-rundel** [comment]
@ValerieRoberts I was able to log in to your project so I'm assuming this issue is resolved, but if not, feel free to reopen.
